/* DICCIONARIO DEL SECTOR: DEMOCRACIA Y TRANSPARENCIA */

window.DICT_SECTOR = Object.assign(window.DICT_SECTOR || {}, {

  /* --- Correcciones y nombres nuevos (lote 2026) --- */
  "Elaboración propia con datos obtenidos de Transparencia Internacional. https://www.transparency.org/en/cpi/2025": "Own elaboration using data from Transparency International. https://www.transparency.org/en/cpi/2025",
  "Delitos de Corrupción Ministerio Público": "Corruption Offences (Public Prosecutor)",
  "Elaboración propia con datos de la solicitud de informacion SOL-MP-3495-2026 (Ministerio Público)": "Own elaboration using data from information request SOL-MP-3495-2026 (Public Prosecutor's Office)",
  "Fiscales Anticorrupción": "Anti-Corruption Prosecutors",
  "Solicitudes IAIP – Respuesta a solicitudes": "IAIP Requests – Response to Requests",
  "IAIP - Respuesta a Solicitudes": "IAIP – Response to Requests",
  "Total de Solicitudes de Información": "Total Information Requests",
  "Solicitudes IAIP – Total": "IAIP Requests – Total",
  "Confianza en Instituciones Públicas": "Trust in Public Institutions",
  "Demandas Contra el Estado": "Lawsuits Against the State",
  "Presupuesto de instituciones de control": "Budget of Oversight Institutions",
  "Recursos de Apelación  TJE": "TJE Appeals",
  "Iglesia Evangélica": "Evangelical Church",
  "Iglesia Católica": "Catholic Church",
  "Congreso Nacional": "National Congress",
  "Partidos Políticos": "Political Parties",
  "Medios de Comunicación": "Media",
  "Ministerio Público": "Public Prosecutor's Office",
  "Corte Suprema de Justicia": "Supreme Court of Justice",
  "CNE": "CNE (National Electoral Council)",
  "Dirección Superior": "Senior Management",
  "Servicios Administrativos": "Administrative Services",
  "Secretaria General": "General Secretariat",
  "Gerencia de Verificación": "Verification Division",
  "Gerencia de Capacitación": "Training Division",
  "Inadmitido": "Inadmissible",
  "Admitido": "Admitted",
  "Pendiente": "Pending",
  "Desistido": "Withdrawn",
  "Por no Interpuestos": "Not filed",
  "Coacción electoral": "Electoral coercion",
  "Coacción y amenaza electoral": "Electoral coercion and threats",
  "Delitos electorales": "Electoral offences",
  "Destrucción de propaganda": "Destruction of campaign material",
  "Falsificación de documentos electorales": "Forgery of electoral documents",
  "Otros delitos electorales": "Other electoral offences",
  "Suplantación de identidad": "Identity impersonation",
  "Suplantación de identidad hondureña para ejercer sufragio": "Impersonation of Honduran identity to vote",
  /* --- Mapas y textos adicionales --- */
  "Denuncias por Corrupción por Departamento": "Corruption Reports by Department",
  "Pasá el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",
  "Pasa el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",

  /* --- Sector --- */
  "Democracia y Transparencia": "Democracy and Transparency",

  /* --- Secciones --- */
  "CORRUPCIÓN Y TRANSPARENCIA": "CORRUPTION AND TRANSPARENCY",
  "TRANSPARENCIA E INFORMACIÓN": "TRANSPARENCY AND INFORMATION",
  "DEMOCRACIA Y OPINIÓN": "DEMOCRACY AND PUBLIC OPINION",
  "JUSTICIA E INSTITUCIONES": "JUSTICE AND INSTITUTIONS",

  /* --- Nombres de indicadores --- */
  "IPC de Corrupción": "Corruption Perceptions Index (CPI)",
  "IPC de Corrupción – Comparativo Regional": "Corruption Perceptions Index \u2013 Regional Comparison",
  "Estado de Derecho WJP – Comparativo": "WJP Rule of Law Index \u2013 Comparison",
  "Denuncias por delitos de corrupción": "Reports of Corruption Offences",
  "Número de Fiscales Anticorrupción desagregado por fiscalías a las que pertenecen (MP)": "Number of Anti-Corruption Prosecutors by Prosecutorial Unit (Public Prosecutor's Office)",
  "Solicitudes IAIP – Estado de respuesta": "IAIP Requests \u2013 Response Status",
  "Total solicitudes IAIP": "Total IAIP Requests",
  "Recursos de revisión IAIP": "IAIP Appeals for Review",
  "Confianza en instituciones públicas": "Trust in Public Institutions",
  "Preferencia por la democracia": "Preference for Democracy",
  "Indice de Democracia": "Democracy Index",
  "Demandas contra el Estado": "Lawsuits Against the State",
  "Presupuesto instituciones de control": "Budget of Oversight Institutions",
  "Presupuesto Congreso Nacional": "National Congress Budget",
  "Recursos Humanos IAIP": "IAIP Staffing",
  "Compensacion en despidos injustificados por año según institucion": "Compensation for Wrongful Dismissal by Year and Institution",
  "Delitos Electorales por Tipo": "Electoral Offences by Type",
  "Recursos de Apelacion TJE": "TJE Appeals",

  /* --- Etiquetas de la barra lateral --- */
  "IPC - Honduras": "CPI \u2013 Honduras",
  "IPC - Comparativo Regional": "CPI \u2013 Regional Comparison",
  "Índice de Estado de Derecho": "Rule of Law Index",
  "Delitos de Corrupción MP": "Corruption Offences (Prosecutor)",
  "Fiscales AntiCorrupcion": "Anti-Corruption Prosecutors",
  "IAIP - Estado de Respuesta": "IAIP \u2013 Response Status",
  "IAIP - Total Solicitudes": "IAIP \u2013 Total Requests",
  "IAIP - Recursos de Revisión": "IAIP \u2013 Appeals for Review",
  "Confianza en Instituciones": "Trust in Institutions",
  "Forma de Gobierno": "Form of Government",
  "Índice de Democracia": "Democracy Index",
  "Demandas en Contra": "Lawsuits Against the State",
  "Presupuesto Inst. Control": "Oversight Institutions Budget",
  "Presupuesto Congreso": "Congress Budget",
  "Compensaciones": "Compensation Payments",
  "Delitos Electorales": "Electoral Offences",
  "Recursos de Apelación TJE": "TJE Appeals",

  /* --- Denominaciones --- */
  "Puntaje 0-100": "Score 0\u2013100",
  "Score 0-1": "Score 0\u20131",
  "Número de denuncias": "Number of reports",
  "Número de fiscales": "Number of prosecutors",
  "Número de solicitudes": "Number of requests",
  "Total de solicitudes": "Total requests",
  "Número de recursos": "Number of appeals",
  "% de confianza": "% expressing trust",
  "Porcentaje (%)": "Percentage (%)",
  "Puntaje 0-10": "Score 0\u201310",
  "Número de demandas": "Number of lawsuits",
  "Millones de Lempiras": "Millions of Lempiras",
  "Cantidad de personal": "Number of staff",
  "Lempiras": "Lempiras",
  "Cantidad de denuncias": "Number of reports",
  "Cantidad de recursos": "Number of appeals",

  /* --- Series --- */
  "Honduras": "Honduras",
  "Costa Rica": "Costa Rica",
  "Guatemala": "Guatemala",
  "El Salvador": "El Salvador",
  "Respondidas en plazo": "Answered on time",
  "Fuera de plazo": "Answered late",
  "No respondidas": "Unanswered",
  "Total": "Total",
  "Contencioso Adm.": "Administrative litigation",
  "Laboral": "Labour",
  "TSC": "TSC (Supreme Audit Tribunal)",
  "PGR": "PGR (Attorney General's Office)",
  "IAIP": "IAIP (Public Information Access Institute)",
  "Presupuesto total": "Total budget",
  "Subvenciones": "Subsidies",
  "2017": "2017",
  "2021": "2021",
  "2025": "2025",

  /* --- Descripciones --- */
  "Puntaje de percepción de corrupción en el sector público de Honduras, según Transparencia Internacional.": "Score for perceived public-sector corruption in Honduras, according to Transparency International.",
  "Comparación del Índice de Percepción de Corrupción de Honduras con otros países de la región.": "Comparison of the Corruption Perceptions Index for Honduras against other countries in the region.",
  "Comparación del puntaje de Estado de Derecho de Honduras con otros países de la región, según el World Justice Project.": "Comparison of the Rule of Law score for Honduras against other countries in the region, according to the World Justice Project.",
  "Cantidad de denuncias por delitos de corrupción registradas ante el Ministerio Público, por persona acusada, delito y departamento.": "Number of reports of corruption offences filed with the Public Prosecutor's Office, by accused person, offence, and department.",
  "Cantidad de fiscales dedicados a casos de corrupción, desagregados por las fiscalías a las que pertenecen.": "Number of prosecutors assigned to corruption cases, disaggregated by the prosecutorial unit to which they belong.",
  "Estado de las solicitudes de acceso a la información pública presentadas ante el IAIP: respondidas en plazo, fuera de plazo o no respondidas.": "Status of public information access requests submitted to the IAIP: answered on time, answered late, or unanswered.",
  "Cantidad total de solicitudes de acceso a la información pública presentadas ante el IAIP.": "Total number of public information access requests submitted to the IAIP.",
  "Cantidad de recursos de revisión presentados ante el IAIP por solicitudes de información no atendidas satisfactoriamente.": "Number of appeals for review filed with the IAIP over information requests that were not satisfactorily resolved.",
  "Nivel de confianza de la población en distintas instituciones públicas, según encuestas de opinión.": "Level of public trust in various public institutions, according to opinion surveys.",
  "Porcentaje de la población que prefiere la democracia como forma de gobierno.": "Share of the population that prefers democracy as a form of government.",
  "Puntaje del Índice de Democracia de Honduras.": "Honduras's score on the Democracy Index.",
  "Cantidad de demandas promovidas en contra del Estado de Honduras, incluyendo casos nacionales e internacionales ante instancias como el CIADI y la CIDH.": "Number of lawsuits brought against the State of Honduras, including domestic and international cases before bodies such as ICSID and the Inter-American Commission on Human Rights.",
  "Presupuesto asignado a las principales instituciones de control del Estado: TSC, PGR, TJE, UFTF, Fiscalía Especial para la Transparencia y Combate a la Corrupción, STLCC, IAIP, CNA y CNE.": "Budget allocated to the main State oversight institutions: TSC, PGR, TJE, UFTF, the Special Prosecutor's Office for Transparency and Anti-Corruption, STLCC, IAIP, CNA, and CNE.",
  "Presupuesto asignado y ejecutado por el Congreso Nacional de la República.": "Budget allocated to and executed by the National Congress of the Republic.",
  "Cantidad de personal del Instituto de Acceso a la Información Pública (IAIP), desagregado por área operativa.": "Number of staff at the Public Information Access Institute (IAIP), disaggregated by operational area.",
  "Monto de las compensaciones económicas pagadas por despidos injustificados, desagregado por institución.": "Amount of financial compensation paid for wrongful dismissal, disaggregated by institution.",
  "Cantidad de denuncias por delitos electorales presentadas ante el Ministerio Público, según el tipo de delito.": "Number of reports of electoral offences filed with the Public Prosecutor's Office, by type of offence.",
  "Estado de los recursos de apelación presentados ante el Tribunal de Justicia Electoral (TJE).": "Status of appeals filed with the Electoral Justice Tribunal (TJE).",

  /* --- Fuentes --- */
  "Elaboracion propia con datos obtenidos de Transparencia Internacional. https://www.transparency.org/en/cpi/2025": "Own elaboration using data from Transparency International. https://www.transparency.org/en/cpi/2025",
  "World Justice Project, Rule of Law Index. https://worldjusticeproject.org/rule-of-law-index/country/2025/Honduras/": "World Justice Project, Rule of Law Index. https://worldjusticeproject.org/rule-of-law-index/country/2025/Honduras/",
  "Elaboracion propia con datos de la solicitud de informacion SOL-MP-3495-2026 (Ministerio Público)": "Own elaboration using data from information request SOL-MP-3495-2026 (Public Prosecutor's Office)",
  "Ministerio Público – División de Recursos Humanos. Datos obtenidos de la solicitud de información SOL-MP-3504-3505-2026": "Public Prosecutor's Office \u2013 Human Resources Division. Data obtained from information request SOL-MP-3504-3505-2026",
  "Instituto de Acceso a la Información Pública (IAIP). Datos obtenidos de la solicitud de información SOL-IAIP-1094-2026": "Public Information Access Institute (IAIP). Data obtained from information request SOL-IAIP-1094-2026",
  "Sondeo de Opinión Pública, Equipo de Reflexión, Investigación y Comunicación (ERIC-SJ). Documento DB Dashboard Transparencia. Se muestra el dato más reciente disponible por institución (2025 o 2024 según disponibilidad).": "Public Opinion Survey, Team for Reflection, Research and Communication (ERIC-SJ). Transparency Dashboard database. The most recent figure available is shown for each institution (2025 or 2024, subject to availability).",
  "Sondeo de Opinión Pública (SOP), Equipo de Reflexión, Investigación y Comunicación (ERIC-SJ). https://www.sop-eric.org/boletines": "Public Opinion Survey (SOP), Team for Reflection, Research and Communication (ERIC-SJ). https://www.sop-eric.org/boletines",
  "The Economist Intelligence Unit (EIU), Democracy Index. https://ourworldindata.org/grapher/democracy-index-eiu?tab=table&time=2024..latest&tableSearch=hondu": "The Economist Intelligence Unit (EIU), Democracy Index. https://ourworldindata.org/grapher/democracy-index-eiu?tab=table&time=2024..latest&tableSearch=hondu",
  "Elaboración propia por medio de solicitud de información a la Procuraduría General de la República (PGR). Respuesta de la solicitud de información Angel David Rodríguez Alvarado.": "Own elaboration through an information request to the Attorney General's Office (PGR). Response to the information request by Angel David Rodr\u00edguez Alvarado.",
  "Elaboración propia con datos de la Secretaría de Finanzas (SEFIN), presupuestos generales de la República 2016-2026, y del Ministerio Público": "Own elaboration using data from the Ministry of Finance (SEFIN), General Budgets of the Republic 2016\u20132026, and from the Public Prosecutor's Office",
  "Informe interno ASJ, Dirección de Transparencia y Democracia, con datos del Congreso Nacional y SEFIN": "Internal ASJ report, Transparency and Democracy Directorate, using data from the National Congress and SEFIN",
  "IAIP, Personal de Recursos Humanos, marzo 2026": "IAIP, Human Resources staffing, March 2026",
  "Instituto de Acceso a la Información Pública (IAIP)": "Public Information Access Institute (IAIP)",
  "Ministerio Público. Datos obtenidos de solicitud de información SOL-MP-3504-3505-2026": "Public Prosecutor's Office. Data obtained from information request SOL-MP-3504-3505-2026",
  "Tribunal de Justicia Electoral (TJE). Datos obtenidos por solicitud de información mediante el Memorandum TJE-SG-85-2026": "Electoral Justice Tribunal (TJE). Data obtained through an information request via Memorandum TJE-SG-85-2026"
});

window.PAGE_TITLE = {es: "Democracia y Transparencia \u2014 Estado del Pa\u00eds Honduras 2026", en: "Democracy and Transparency \u2014 State of the Nation Honduras 2026"};
