/* DICCIONARIO DEL SECTOR: ECONOMIA */

window.DICT_SECTOR = Object.assign(window.DICT_SECTOR || {}, {

  /* --- Correcciones y nombres nuevos (lote 2026) --- */
  "Empleo total frente a empleo formal": "Total vs. Formal Employment",
  "Ingreso per Cápita": "Income Per Capita",
  "Pobreza total y pobreza extrema": "Total and Extreme Poverty",
  "Elaboración propia con datos obtenidos del Instituto Nacional de Estadisticas y Secretaria de Finanzas(datos abiertos). Nota metodológica: Gasto social se compone de la suma del gasto según función SERVICIOS DE SALUD, EDUCACION, INVESTIGACION, CULTURA Y ACTIVIDADES RECREATIVAS y PROTECCION SOCIAL.": "Own elaboration using data from the National Institute of Statistics and the Ministry of Finance (open data). Methodological note: social spending is the sum of expenditure under the functions HEALTH SERVICES, EDUCATION, RESEARCH, CULTURE AND RECREATION, and SOCIAL PROTECTION.",
  "Ingreso por remesas": "Remittance Income",
  "Población migrante en el extranjero": "Migrant Population Abroad",
  "Subsidios Anuales": "Annual Subsidies",
  "Crecimiento del PIB annual de Honduras": "Annual GDP Growth, Honduras",
  "Producto Interno Bruta según Actividad Económica (2025)": "Gross Domestic Product by Economic Activity (2025)",
  "Inflación Interanual de Honduras": "Year-on-Year Inflation, Honduras",
  "Ingreso y gasto tributario": "Tax Revenue and Expenditure",
  "Índice de Transparencia de Presupuesto": "Budget Transparency Index",
  "Salario mínimo e ingreso real": "Minimum Wage and Actual Earnings",
  "Agricultura y Pesca": "Agriculture and Fishing",
  "Minas y Canteras": "Mining and Quarrying",
  "Manufactura": "Manufacturing",
  "Electricidad y Agua": "Electricity and Water",
  "Construcción": "Construction",
  "Comercio": "Trade",
  "Hoteles y Restaurantes": "Hotels and Restaurants",
  "Transporte": "Transport",
  "Comunicaciones": "Communications",
  "Intermediación Financiera": "Financial Intermediation",
  "Vivienda": "Housing",
  "Actividades Inmobiliarias": "Real Estate Activities",
  "Administración Pública": "Public Administration",
  "Educación": "Education",
  "Salud": "Health",
  "Servicios Comunitarios": "Community Services",
  "SIFMI": "FISIM",
  "Transparencia": "Transparency",
  "Participación Pública": "Public Participation",
  "Vigilancia del Presupuesto": "Budget Oversight",

  /* --- Sector --- */
  "Economía": "Economy",

  /* --- Secciones --- */
  "EMPLEO Y TRABAJO": "EMPLOYMENT AND LABOUR",
  "BIENESTAR Y POBREZA": "WELLBEING AND POVERTY",
  "ÍNDICES Y COMPETITIVIDAD": "INDICES AND COMPETITIVENESS",
  "MACROECONOMÍA": "MACROECONOMICS",

  /* --- Nombres de indicadores --- */
  "Empleo total vs formal": "Total vs. Formal Employment",
  "Porcentaje de empleo formal": "Share of Formal Employment",
  "Tasa de desempleo abierto": "Open Unemployment Rate",
  "Salario Minimo": "Minimum Wage",
  "Productividad Laboral": "Labour Productivity",
  "Ingreso Percapita": "Income Per Capita",
  "Pobreza total vs extrema": "Total vs. Extreme Poverty",
  "Gasto social del gobierno": "Government Social Spending",
  "Remesas familiares recibidas por Honduras 2003-2025, en valores corrientes y en proporción al PIB": "Family Remittances Received by Honduras 2003\u20132025, in Current Values and as a Share of GDP",
  "Poblacion hondureña migrante que reside en el extranjero": "Honduran Migrant Population Residing Abroad",
  "Subsidios anuales en millones de lempiras": "Annual Subsidies in Millions of Lempiras",
  "Indice de Progreso Social": "Social Progress Index",
  "Indice deLibertad Economica": "Index of Economic Freedom",
  "Indice de Estado de Derecho": "Rule of Law Index",
  "Crecimiento del PIB annual (% annual) Honduras": "Annual GDP Growth (% per year), Honduras",
  "Producto Interno Bruto de Honduras según composición por actividad económica (2025)": "Gross Domestic Product of Honduras by Economic Activity (2025)",
  "Inflacion Interanual de Honduras": "Year-on-Year Inflation in Honduras",
  "Deuda Publica": "Public Debt",
  "Inversión pública ejecutada según su categoría, valores en millones de lempiras": "Public Investment Executed by Category, in Millions of Lempiras",
  "Gasto tributario de personas jurídicas en Honduras (en millones de lempiras) 2020-2024": "Tax Expenditure on Legal Entities in Honduras (millions of Lempiras), 2020\u20132024",
  "Indice de Transparencia de Presupuesto": "Budget Transparency Index",
  "Comparación entre el salario mínimo promedio y los ingresos que reciben los trabajadores asalariados del sector privado 2004-2025": "Comparison Between the Average Minimum Wage and Actual Earnings of Private-Sector Wage Workers, 2004\u20132025",

  /* --- Etiquetas de la barra lateral --- */
  "Empleo Formal - Cantidad": "Formal Employment \u2013 Count",
  "Empleo Formal - Porcentaje": "Formal Employment \u2013 Share",
  "Desempleo": "Unemployment",
  "Salario Mínimo": "Minimum Wage",
  "Pobreza (Total y Extrema)": "Poverty (Total and Extreme)",
  "Gasto Social del Gobierno": "Government Social Spending",
  "Remesas": "Remittances",
  "Migración": "Migration",
  "Subsidios": "Subsidies",
  "Índice de Progreso Social": "Social Progress Index",
  "Índice de Libertad Económica": "Index of Economic Freedom",
  "Estado de Derecho": "Rule of Law",
  "Crecimiento del PIB": "GDP Growth",
  "PIB Según Actividad Económica": "GDP by Economic Activity",
  "Inflación Interanual": "Year-on-Year Inflation",
  "Deuda Pública": "Public Debt",
  "Inversión Pública": "Public Investment",
  "Gasto Tributario": "Tax Expenditure",
  "Ind.Transparencia Presupuesto": "Budget Transparency Index",
  "Comparación Salario Mínimo": "Minimum Wage Comparison",

  /* --- Denominaciones --- */
  "Trabajadores": "Workers",
  "Porcentaje (%)": "Percentage (%)",
  "Lempiras (mensual)": "Lempiras (monthly)",
  "USD por hora trabajada": "USD per hour worked",
  "USD anuales": "USD per year",
  "% de hogares": "% of households",
  "Miles de millones de Lempiras": "Billions of Lempiras",
  "Miles de USD": "Thousands of USD",
  "Número de emigrantes": "Number of emigrants",
  "Millones de Lempiras": "Millions of Lempiras",
  "Puntaje 0-100": "Score 0\u2013100",
  "Score 0-1": "Score 0\u20131",
  "Porcentaje anual": "Percentage per year",
  "Millones de Lempiras (2025)": "Millions of Lempiras (2025)",
  "Variación porcentual (%)": "Percentage change (%)",
  "Porcentaje del PIB": "Share of GDP",
  "Lempiras nominales mensuales": "Nominal Lempiras per month",

  /* --- Series --- */
  "Empleo total": "Total employment",
  "Cotizantes IHSS (formal)": "IHSS contributors (formal)",
  "Pobreza total": "Total poverty",
  "Pobreza extrema": "Extreme poverty",
  "Honduras": "Honduras",
  "Costa Rica": "Costa Rica",
  "Guatemala": "Guatemala",
  "El Salvador": "El Salvador",
  "Inversión Productiva": "Productive investment",
  "Inversión Social": "Social investment",
  "Ingreso tributario": "Tax revenue",
  "Gasto tributario": "Tax expenditure",
  "Salario mínimo promedio": "Average minimum wage",
  "Ingreso promedio asalariados privados": "Average earnings, private-sector wage workers",

  /* --- Descripciones --- */
  "Cantidad de trabajadores empleados formalmente frente al total de empleados en Honduras.": "Number of workers in formal employment compared with total employment in Honduras.",
  "Porcentaje de trabajadores que cuentan con un empleo formal (cotizante al IHSS) respecto al total de empleados.": "Share of workers in formal employment (contributing to the IHSS) as a proportion of total employment.",
  "Porcentaje de la población económicamente activa que se encuentra sin empleo y buscando trabajo.": "Share of the economically active population who are unemployed and seeking work.",
  "Evolución anual del salario mínimo nominal en Honduras.": "Annual trend in the nominal minimum wage in Honduras.",
  "Valor generado por hora trabajada en la economía hondureña, medido en dólares.": "Value generated per hour worked in the Honduran economy, measured in US dollars.",
  "Ingreso promedio anual por habitante en Honduras, medido en dólares.": "Average annual income per inhabitant in Honduras, measured in US dollars.",
  "Porcentaje de hogares en situación de pobreza total y en pobreza extrema.": "Share of households living in total poverty and in extreme poverty.",
  "Gasto social compuesto por la suma del gasto en servicios de salud, educación, investigación, cultura y actividades recreativas, y protección social.": "Social spending, comprising the sum of expenditure on health services, education, research, culture and recreation, and social protection.",
  "Monto de remesas familiares recibidas por Honduras y su proporción respecto al Producto Interno Bruto (PIB).": "Value of family remittances received by Honduras and their share of Gross Domestic Product (GDP).",
  "Cantidad estimada de hondureños que residen fuera del país.": "Estimated number of Hondurans residing outside the country.",
  "Monto de los subsidios otorgados por el gobierno a empresas privadas y públicas, y ayuda social a personas.": "Value of subsidies granted by the government to private and public enterprises, and of social assistance to individuals.",
  "Puntaje del Índice de Progreso Social de Honduras, que mide el bienestar de la población más allá del ingreso económico.": "Honduras's score on the Social Progress Index, which measures population wellbeing beyond economic income.",
  "Puntaje del Índice de Libertad Económica de Honduras.": "Honduras's score on the Index of Economic Freedom.",
  "Puntaje del Índice de Estado de Derecho de Honduras.": "Honduras's score on the Rule of Law Index.",
  "Porcentaje de crecimiento anual del Producto Interno Bruto (PIB) de Honduras.": "Annual percentage growth in the Gross Domestic Product (GDP) of Honduras.",
  "Composición del Producto Interno Bruto (PIB) de Honduras según la actividad económica que lo genera.": "Composition of the Gross Domestic Product (GDP) of Honduras by the economic activity generating it.",
  "Variación porcentual de los precios al consumidor en Honduras respecto al mismo mes del año anterior.": "Percentage change in consumer prices in Honduras relative to the same month of the previous year.",
  "Deuda pública de Honduras como porcentaje del Producto Interno Bruto (PIB).": "Public debt of Honduras as a share of Gross Domestic Product (GDP).",
  "Inversión pública ejecutada por el gobierno de Honduras, según su categoría de destino.": "Public investment executed by the Government of Honduras, by category of destination.",
  "Monto del gasto tributario (exoneraciones y beneficios fiscales) otorgado a personas jurídicas en Honduras.": "Value of tax expenditure (exemptions and fiscal benefits) granted to legal entities in Honduras.",
  "Encuesta de Presupuesto Abierto: mide transparencia, participación pública y vigilancia del presupuesto por parte del Congreso y la Entidad Fiscalizadora Superior.": "Open Budget Survey: measures budget transparency, public participation, and oversight by Congress and the Supreme Audit Institution.",
  "Comparación entre el salario mínimo promedio y los ingresos que efectivamente reciben los trabajadores asalariados del sector privado.": "Comparison between the average minimum wage and the earnings actually received by private-sector wage workers.",

  /* --- Fuentes --- */
  "Instituto Hondureño de Seguridad Social (IHSS) e Instituto Nacional de Estadística (INE)": "Honduran Social Security Institute (IHSS) and National Institute of Statistics (INE)",
  "Elaboración propia con datos del Instituto Nacional de Estadísticas-Encuesta Permanente de Hogares 2016 - 2026": "Own elaboration using data from the National Institute of Statistics \u2013 Permanent Household Survey, 2016\u20132026",
  "Secretaria de Trabajo y Seguridad Social, y la GACETA": "Ministry of Labour and Social Security, and La Gaceta (Official Gazette)",
  "INE": "INE (National Institute of Statistics)",
  "Banco Mundial / BCH": "World Bank / Central Bank of Honduras",
  "Instituto Nacional de Estadística (INE), LXXXIII Encuesta Permanente de Hogares de Propósitos Múltiples, Julio 2025. Nota: Solo incluye los hogares que declaran ingreso. No se realizó encuesta en 2000; datos no disponibles para 2020 y 2022.": "National Institute of Statistics (INE), 83rd Permanent Multi-Purpose Household Survey, July 2025. Note: includes only households reporting income. No survey was conducted in 2000; data are unavailable for 2020 and 2022.",
  "Elaboracion propia con datos obtenidos del Instituto Nacional de Estadisticas y Secretaria de Finanzas(datos abiertos). Nota metodológica: Gasto social se compone de la suma del gasto según función SERVICIOS DE SALUD, EDUCACION, INVESTIGACION, CULTURA Y ACTIVIDADES RECREATIVAS y PROTECCION SOCIAL.": "Own elaboration using data from the National Institute of Statistics and the Ministry of Finance (open data). Methodological note: social spending is the sum of expenditure under the functions HEALTH SERVICES, EDUCATION, RESEARCH, CULTURE AND RECREATION, and SOCIAL PROTECTION.",
  "Elaboración propia. Datos de remesas familiares de la Balanza Cambiaria y del producto Interno Bruto (PIB) del Banco Central de Honduras para el período 2015–2025. Nota Metodológica: El porcentaje de las remesas respecto al PIB se calcula dividiendo el monto anual de las remesas entre el PIB anual de cada año, para el período 2015–2021.": "Own elaboration. Family remittance data from the Foreign Exchange Balance and GDP figures from the Central Bank of Honduras for the period 2015\u20132025. Methodological note: remittances as a share of GDP are calculated by dividing the annual remittance total by annual GDP for each year, for the period 2015\u20132021.",
  "Elaboración propia con datos de la ONU DAES. Nota metodológica: El indicador se calculó como la proporción de emigrantes internacionales hondureños respecto a la población total del país, dividiendo el número estimado de hondureños residentes en el extranjero entre la población total nacional y multiplicando el resultado por 100: (1,400,000 / 10,039,862) × 100. Se estima que el 13.9% de los hondureños reside en el extranjero, equivalente a aproximadamente 1 de cada 7 habitantes del país.": "Own elaboration using data from UN DESA. Methodological note: the indicator was calculated as the share of Honduran international emigrants relative to the country's total population, dividing the estimated number of Hondurans residing abroad by the total national population and multiplying by 100: (1,400,000 / 10,039,862) \u00d7 100. An estimated 13.9% of Hondurans live abroad, equivalent to roughly 1 in every 7 inhabitants.",
  "Elaboración propia con datos de la Secretaría de Estado en los Despachos de Finanzas (SEFIN) mediante solicitud de información SOL-SEFIN-3585-2026. Los objetos de gasto incluidos son subsidios a empresas privadas no financieras (51410), Subsidios a empresas publicas no financieras (52310), Ayuda Social a Personas (51220) y Subsidios a Empresas Públicas Financieras (55320). Nota metodológica: Los subsidios corresponden a transferencias y apoyos fiscales registrados en el Presupuesto General de la República. Los montos están expresados en millones de lempiras corrientes. Los datos de 2022 y 2023 corresponden a información parcial disponible en SEFIN.": "Own elaboration using data from the Ministry of Finance (SEFIN) obtained through information request SOL-SEFIN-3585-2026. Expenditure lines included are subsidies to private non-financial enterprises (51410), subsidies to public non-financial enterprises (52310), social assistance to individuals (51220), and subsidies to public financial enterprises (55320). Methodological note: subsidies correspond to transfers and fiscal support recorded in the General Budget of the Republic. Amounts are expressed in current millions of Lempiras. Figures for 2022 and 2023 reflect partial information available from SEFIN.",
  "Elaboración propia con datos del Índice de Progreso Social de Social Progress Imperative y INCAE. https://www.socialprogress.org/indice-de-progreso-social-global-alti-2025": "Own elaboration using Social Progress Index data from Social Progress Imperative and INCAE. https://www.socialprogress.org/indice-de-progreso-social-global-alti-2025",
  "The Heritage Foundation, Index of Economic Freedom. https://economicfreedom.heritage.org/pages/all-country-scores": "The Heritage Foundation, Index of Economic Freedom. https://economicfreedom.heritage.org/pages/all-country-scores",
  "World Justice Project, Rule of Law Index. https://worldjusticeproject.org/rule-of-law-index/country/2025/Honduras/": "World Justice Project, Rule of Law Index. https://worldjusticeproject.org/rule-of-law-index/country/2025/Honduras/",
  "Elaboración propia con datos del Banco Central de Honduras, cuadros del PIB según Actividad Económica (2006-2025)": "Own elaboration using Central Bank of Honduras data, GDP by Economic Activity tables (2006\u20132025)",
  "Elaboración propia con datos del Banco Central de Honduras, cuadros del PIB según Actividad Económica 2025": "Own elaboration using Central Bank of Honduras data, GDP by Economic Activity tables, 2025",
  "Elaboración propia con datos del Banco Central de Honduras, cuadros del índice de precios al consumidor 2016 - 2026": "Own elaboration using Central Bank of Honduras data, Consumer Price Index tables, 2016\u20132026",
  "Elaboración propia con datos del Informe de Deuda Pública de la Administración Central de Honduras de la Secretaría de Finanzas del 2016-2025": "Own elaboration using the Central Government Public Debt Report of Honduras from the Ministry of Finance, 2016\u20132025",
  "Elaboración propia con datos del Informe General de la Inversión Pública de la Secretaría de Estado en los Despachos de Finanzas (SEFIN) del 2020-2025.": "Own elaboration using the General Report on Public Investment from the Ministry of Finance (SEFIN), 2020\u20132025.",
  "Elaboración propia. Los datos para el gasto tributario se obtuvieron del Proyecto de Presupuesto General de la República Ejercicio Fiscal (2021-2025). Los datos de recaudación se obtuvieron del Sistema de Administración de Rentas (SAR) mediante solicitud de información SOL-SAR-1150-2026.": "Own elaboration. Tax expenditure data were taken from the Draft General Budget of the Republic for fiscal years 2021\u20132025. Revenue collection data were obtained from the Revenue Administration Service (SAR) through information request SOL-SAR-1150-2026.",
  "Elaboración propia con datos de la Encuesta de Presupuesto Abierto 2023. https://biblioteca.fosdeh.hn/books/la-encuesta-de-presupuesto-abierto-2023/": "Own elaboration using data from the Open Budget Survey 2023. https://biblioteca.fosdeh.hn/books/la-encuesta-de-presupuesto-abierto-2023/",
  "Elaboración propia con datos del INE-EPHPM y de la Secretaría de Trabajo y Seguridad Social": "Own elaboration using data from the INE Permanent Multi-Purpose Household Survey and the Ministry of Labour and Social Security"
});

window.PAGE_TITLE = {es: "Econom\u00eda \u2014 Estado del Pa\u00eds Honduras 2026", en: "Economy \u2014 State of the Nation Honduras 2026"};
