/* DICCIONARIO DEL SECTOR: EDUCACION */

window.DICT_SECTOR = Object.assign(window.DICT_SECTOR || {}, {

  /* --- Correcciones y nombres nuevos (lote 2026) --- */
  "Matrícula escolar (prebásica)": "School Enrolment (pre-primary)",
  "Matrícula escolar (básica)": "School Enrolment (basic)",
  "Matrícula escolar (media)": "School Enrolment (secondary)",
  "Matrícula escolar total": "Total School Enrolment",
  "Cobertura educativa bruta (prebásica)": "Gross Education Coverage (pre-primary)",
  "Cobertura educativa bruta (básica)": "Gross Education Coverage (basic)",
  "Cobertura educativa bruta (media)": "Gross Education Coverage (secondary)",
  "Cobertura educativa bruta total": "Total Gross Education Coverage",
  "Exclusión escolar": "Out-of-School Children",
  "Enrolamiento privado (prebásica)": "Private Enrolment (pre-primary)",
  "Enrolamiento privado (básica)": "Private Enrolment (basic)",
  "Enrolamiento privado (media)": "Private Enrolment (secondary)",
  "Enrolamiento privado total": "Total Private Enrolment",
  "Años de estudio promedio (hombres)": "Average Years of Schooling (men)",
  "Elaboración propia con datos obtenidos del Instituto Nacional de Estadisticas": "Own elaboration using data from the National Institute of Statistics",
  "Años de estudio promedio (mujeres)": "Average Years of Schooling (women)",
  "Años de estudio promedio": "Average Years of Schooling",
  "Analfabetismo (hombres)": "Illiteracy (men)",
  "Analfabetismo (mujeres)": "Illiteracy (women)",
  "Analfabetismo total": "Total Illiteracy",
  "Analfabetismo (quintil 1)": "Illiteracy (quintile 1)",
  "Analfabetismo (quintil 2)": "Illiteracy (quintile 2)",
  "Analfabetismo (quintil 3)": "Illiteracy (quintile 3)",
  "Analfabetismo (quintil 4)": "Illiteracy (quintile 4)",
  "Analfabetismo (quintil 5)": "Illiteracy (quintile 5)",
  "Tasa de repitencia (básica)": "Repetition Rate (basic)",
  "Tasa de repitencia (media)": "Repetition Rate (secondary)",
  "Tasa de repitencia total": "Total Repetition Rate",
  "Tasa de reprobación (prebásica)": "Failure Rate (pre-primary)",
  "Tasa de reprobación (básica)": "Failure Rate (basic)",
  "Tasa de reprobación (media)": "Failure Rate (secondary)",
  "Tasa de reprobación total": "Total Failure Rate",
  "Desempeño en matemáticas (3er grado)": "Mathematics Performance (grade 3)",
  "Desempeño en matemáticas (6to grado)": "Mathematics Performance (grade 6)",
  "Desempeño en matemáticas (9no grado)": "Mathematics Performance (grade 9)",
  "Graduados de noveno grado": "Grade 9 Graduates",
  "Graduados de duodécimo grado": "Grade 12 Graduates",
  "Graduados totales (básica y media)": "Total Graduates (basic and secondary)",
  "Alumnos por maestro (prebásica)": "Pupils per Teacher (pre-primary)",
  "Alumnos por maestro (básica)": "Pupils per Teacher (basic)",
  "Alumnos por maestro total": "Total Pupils per Teacher",
  "Cobertura de merienda escolar (prebásica)": "School Meal Coverage (pre-primary)",
  "Cobertura de merienda escolar (básica)": "School Meal Coverage (basic)",
  "Cobertura de merienda escolar total": "Total School Meal Coverage",
  "No estudian: falta de recursos económicos": "Out of school: lack of financial resources",
  "No estudian: no quieren seguir estudiando": "Out of school: do not wish to continue",
  "No estudian: problemas familiares o de salud": "Out of school: family or health problems",
  "No estudian: por trabajo": "Out of school: work",
  "Docentes de educación prebásica": "Pre-primary Teachers",
  "Docentes de educación básica": "Basic Education Teachers",
  "Docentes de educación media": "Secondary Teachers",
  "Docentes de la Secretaría de Educación": "Ministry of Education Teachers",
  "Docentes en educación superior (mujeres)": "Higher Education Teachers (women)",
  "Elaboración propia con datos obtenidos del  Banco Central de Honduras y Honduras en cifras": "Own elaboration using data from the Central Bank of Honduras and Honduras en Cifras",
  "Docentes en educación superior (hombres)": "Higher Education Teachers (men)",
  "Docentes en educación superior": "Higher Education Teachers",
  "Estudiantes en educación superior (público)": "Higher Education Students (public)",
  "Elaboración propia con datos obtenidos de la Universidad Nacional Autónoma de Honduras": "Own elaboration using data from the National Autonomous University of Honduras",
  "Estudiantes en educación superior (privado)": "Higher Education Students (private)",
  "Estudiantes en educación superior": "Higher Education Students",
  "Textos escolares entregados": "School Textbooks Delivered",
  "Elaboración propia con datos obtenidos de Red Solidaria": "Own elaboration using data from Red Solidaria",
  "Presupuesto en educación (% del PIB)": "Education Budget (% of GDP)",
  "Presupuesto en educación (% del presupuesto nacional)": "Education Budget (% of National Budget)",
  "Presupuesto - % del presupuesto nacional": "Budget – % of National Budget",
  "Presupuesto vigente en educación": "Current Education Budget",
  "Cobertura educativa bruta por nivel": "Gross Education Coverage by Level",
  "Graduados por nivel educativo": "Graduates by Education Level",
  "Razones por las que los menores no estudian": "Reasons children are out of school",
  "Docentes por nivel educativo": "Teachers by Education Level",
  "Docentes en educación superior por género": "Higher Education Teachers by Gender",
  "Textos escolares entregados por tipo": "School Textbooks Delivered by Type",
  "Gasto ejecutado por nivel educativo": "Executed Spending by Education Level",
  "Presupuesto ejecutado por objeto de gasto": "Executed Budget by Expenditure Category",
  "Gasto vigente por nivel educativo": "Current Spending by Education Level",
  "Presupuesto vigente por objeto de gasto": "Current Budget by Expenditure Category",
  "Ejecución presupuestaria por objeto de gasto": "Budget Execution by Expenditure Category",
  /* --- Mapas y textos adicionales --- */
  "Matrícula escolar por departamento": "School Enrolment by Department",
  "Exclusión escolar por departamento": "Out-of-School Children by Department",
  "Pasá el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",
  "Pasa el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",

  /* --- Sector --- */
  "Educación": "Education",

  /* --- Secciones --- */
  "COBERTURA Y ACCESO": "COVERAGE AND ACCESS",
  "CALIDAD EDUCATIVA": "EDUCATION QUALITY",
  "RECURSOS": "RESOURCES",

  /* --- Nombres de indicadores --- */
  "Matrícula escolar-Prebásica": "School Enrolment – Pre-primary",
  "Matrícula escolar-Básica": "School Enrolment – Basic",
  "Matrícula escolar-Media": "School Enrolment – Secondary",
  "Matrícula escolar-Total": "School Enrolment – Total",
  "Cobertura educativa bruta-Prebásica": "Gross Education Coverage – Pre-primary",
  "Cobertura educativa bruta-Básica": "Gross Education Coverage – Basic",
  "Cobertura educativa bruta-Media": "Gross Education Coverage – Secondary",
  "Cobertura educativa bruta-Total": "Gross Education Coverage – Total",
  "Exclusión escolar-Total": "Out-of-School Children – Total",
  "Porcentaje de enrolamiento privado-Prebásica": "Share of Private Enrolment – Pre-primary",
  "Porcentaje de enrolamiento privado-Básica": "Share of Private Enrolment – Basic",
  "Porcentaje de enrolamiento privado-Media": "Share of Private Enrolment – Secondary",
  "Porcentaje de enrolamiento privado-Total": "Share of Private Enrolment – Total",
  "Años de estudio promedio-Hombres": "Average Years of Schooling – Men",
  "Años de estudio promedio-Mujeres": "Average Years of Schooling – Women",
  "Años de estudio promedio-Total": "Average Years of Schooling – Total",
  "Porcentaje de analfabetismo en la población-Hombre": "Illiteracy Rate in the Population – Men",
  "Porcentaje de analfabetismo en la población-Mujer": "Illiteracy Rate in the Population – Women",
  "Porcentaje de analfabetismo en la población-Total": "Illiteracy Rate in the Population – Total",
  "Porcentaje de analfabetismo según quintil de ingresos-Quintil 1": "Illiteracy Rate by Income Quintile – Quintile 1",
  "Porcentaje de analfabetismo según quintil de ingresos-Quintil 2": "Illiteracy Rate by Income Quintile – Quintile 2",
  "Porcentaje de analfabetismo según quintil de ingresos-Quintil 3": "Illiteracy Rate by Income Quintile – Quintile 3",
  "Porcentaje de analfabetismo según quintil de ingresos-Quintil 4": "Illiteracy Rate by Income Quintile – Quintile 4",
  "Porcentaje de analfabetismo según quintil de ingresos-Quintil 5": "Illiteracy Rate by Income Quintile – Quintile 5",
  "Tasa de repitencia-Básica": "Repetition Rate – Basic",
  "Tasa de repitencia-Media": "Repetition Rate – Secondary",
  "Tasa de repitencia-Total": "Repetition Rate – Total",
  "Tasa de reprobación-Prebásica": "Failure Rate – Pre-primary",
  "Tasa de reprobación-Básica": "Failure Rate – Basic",
  "Tasa de reprobación-Media": "Failure Rate – Secondary",
  "Tasa de reprobación-Total": "Failure Rate – Total",
  "Porcentaje de estudiantes por nivel de desempeño en matemáticas-3er Grado": "Share of Students by Mathematics Performance Level – Grade 3",
  "Porcentaje de estudiantes por nivel de desempeño en matemáticas-6to Grado": "Share of Students by Mathematics Performance Level – Grade 6",
  "Porcentaje de estudiantes por nivel de desempeño en matemáticas-9to Grado": "Share of Students by Mathematics Performance Level – Grade 9",
  "Graduados históricos-Noveno Grado": "Historical Graduates – Grade 9",
  "Graduados históricos-Duodécimo Grado": "Historical Graduates – Grade 12",
  "Graduados históricos-Total (Básica y Media)": "Historical Graduates – Total (Basic and Secondary)",
  "Promedio de alumnos por maestro-Prebásica": "Average Pupils per Teacher – Pre-primary",
  "Promedio de alumnos por maestro-Básica": "Average Pupils per Teacher – Basic",
  "Promedio de alumnos por maestro-Total": "Average Pupils per Teacher – Total",
  "Cobertura Merienda Escolar-Prebásica": "School Meal Programme Coverage – Pre-primary",
  "Cobertura Merienda Escolar-Básica": "School Meal Programme Coverage – Basic",
  "Cobertura Merienda Escolar-Total": "School Meal Programme Coverage – Total",
  "Razón principal por la cual menores entre los 6 y 17 años no están estudiando-Falta de recursos económicos": "Main Reason Children Aged 6–17 Are Not in School – Lack of financial resources",
  "Razón principal por la cual menores entre los 6 y 17 años no están estudiando-No quiere seguir estudiando": "Main Reason Children Aged 6–17 Are Not in School – Does not wish to continue studying",
  "Razón principal por la cual menores entre los 6 y 17 años no están estudiando-Por problemas familiares o de salud": "Main Reason Children Aged 6–17 Are Not in School – Family or health problems",
  "Razón principal por la cual menores entre los 6 y 17 años no están estudiando-Por trabajo": "Main Reason Children Aged 6–17 Are Not in School – Work",
  "Número de docentes de la secretaria de educación-Educación Pre-Básica": "Number of Ministry of Education Teachers – Pre-primary education",
  "Número de docentes de la secretaria de educación-Educación Básica": "Number of Ministry of Education Teachers – Basic education",
  "Número de docentes de la secretaria de educación-Educación Media": "Number of Ministry of Education Teachers – Secondary education",
  "Número de docentes de la secretaria de educación-Total": "Number of Ministry of Education Teachers – Total",
  "Docentes en educación superior-Femenino": "Higher Education Teaching Staff – Female",
  "Docentes en educación superior-Masculino": "Higher Education Teaching Staff – Male",
  "Docentes en educación superior-Total": "Higher Education Teaching Staff – Total",
  "Número de estudiantes en educación superior-Público": "Number of Higher Education Students – Public",
  "Número de estudiantes en educación superior-Privado": "Number of Higher Education Students – Private",
  "Número de estudiantes en educación superior-Total": "Number of Higher Education Students – Total",
  "Cantidad de textos escolares entregados-Total": "School Textbooks Delivered – Total",
  "Presupuesto en educación-Porcentaje del PIB": "Education Budget – Share of GDP",
  "Presupuesto en educación-Porcentaje del Presupuesto General": "Education Budget – Share of the National Budget",
  "Presupuesto en educación-Presupuesto Vigente": "Education Budget – Current Budget",
  "Matrícula escolar por nivel": "School Enrolment by Level",
  "Cobertura bruta por nivel": "Gross Coverage by Level",
  "Enrolamiento privado por nivel": "Private Enrolment by Level",
  "Años de estudio promedio por género": "Average Years of Schooling by Gender",
  "Analfabetismo por género": "Illiteracy by Gender",
  "Analfabetismo por quintil de ingresos": "Illiteracy by Income Quintile",
  "Tasa de repitencia por nivel": "Repetition Rate by Level",
  "Tasa de reprobación por nivel": "Failure Rate by Level",
  "Desempeño en matemáticas por grado": "Mathematics Performance by Grade",
  "Graduados históricos por nivel": "Historical Graduates by Level",
  "Alumnos por maestro por nivel": "Pupils per Teacher by Level",
  "Razones por las que no estudian (6-17 años)": "Reasons for Not Attending School (ages 6–17)",
  "Docentes SEDUC por nivel": "Ministry of Education Teachers by Level",
  "Docentes educación superior por género": "Higher Education Teachers by Gender",
  "Estudiantes educación superior": "Higher Education Students",
  "Presupuesto en educación": "Education Budget",
  "Cantidad de textos escolares entregados por tipo": "School Textbooks Delivered by Recipient Type",
  "Gasto gubernamental ejecutado por nivel educativo": "Executed Government Spending by Education Level",
  "Presupuesto ejecutado de la Secretaría de Educación por objeto de gasto": "Executed Ministry of Education Budget by Expenditure Category",
  "Gasto gubernamental vigente por nivel educativo": "Current Government Spending by Education Level",
  "Presupuesto vigente de la Secretaría de Educación por objeto de gasto": "Current Ministry of Education Budget by Expenditure Category",
  "Porcentaje de ejecución presupuestaria por objeto de gasto": "Budget Execution Rate by Expenditure Category",

  /* --- Etiquetas de la barra lateral --- */
  "Matrícula Prebásica": "Enrolment – Pre-primary",
  "Matrícula Básica": "Enrolment – Basic",
  "Matrícula Media": "Enrolment – Secondary",
  "Matrícula Total": "Enrolment – Total",
  "Cobertura Prebásica": "Coverage – Pre-primary",
  "Cobertura Básica": "Coverage – Basic",
  "Cobertura Media": "Coverage – Secondary",
  "Cobertura Total": "Coverage – Total",
  "Exclusión Escolar": "Out-of-School Children",
  "Enrolamiento Privado Prebásica": "Private Enrolment – Pre-primary",
  "Enrolamiento Privado Básica": "Private Enrolment – Basic",
  "Enrolamiento Privado Media": "Private Enrolment – Secondary",
  "Enrolamiento Privado Total": "Private Enrolment – Total",
  "Años de Estudio - Hombres": "Years of Schooling – Men",
  "Años de Estudio - Mujeres": "Years of Schooling – Women",
  "Años de Estudio - Total": "Years of Schooling – Total",
  "Analfabetismo - Hombres": "Illiteracy – Men",
  "Analfabetismo - Mujeres": "Illiteracy – Women",
  "Analfabetismo - Total": "Illiteracy – Total",
  "Analfabetismo - Quintil 1": "Illiteracy – Quintile 1",
  "Analfabetismo - Quintil 2": "Illiteracy – Quintile 2",
  "Analfabetismo - Quintil 3": "Illiteracy – Quintile 3",
  "Analfabetismo - Quintil 4": "Illiteracy – Quintile 4",
  "Analfabetismo - Quintil 5": "Illiteracy – Quintile 5",
  "Repitencia Básica": "Repetition – Basic",
  "Repitencia Media": "Repetition – Secondary",
  "Repitencia Total": "Repetition – Total",
  "Reprobación Prebásica": "Failure – Pre-primary",
  "Reprobación Básica": "Failure – Basic",
  "Reprobación Media": "Failure – Secondary",
  "Reprobación Total": "Failure – Total",
  "Matemáticas - 3er Grado": "Mathematics – Grade 3",
  "Matemáticas - 6to Grado": "Mathematics – Grade 6",
  "Matemáticas - 9no Grado": "Mathematics – Grade 9",
  "Graduados - Noveno Grado": "Graduates – Grade 9",
  "Graduados - Duodécimo Grado": "Graduates – Grade 12",
  "Graduados - Total": "Graduates – Total",
  "Alumnos por Maestro - Prebásica": "Pupils per Teacher – Pre-primary",
  "Alumnos por Maestro - Básica": "Pupils per Teacher – Basic",
  "Alumnos por Maestro - Total": "Pupils per Teacher – Total",
  "Merienda Escolar - Prebásica": "School Meals – Pre-primary",
  "Merienda Escolar - Básica": "School Meals – Basic",
  "Merienda Escolar - Total": "School Meals – Total",
  "Razón: Falta de Recursos": "Reason: Lack of Resources",
  "Razón: No Quiere Estudiar": "Reason: Does Not Wish to Study",
  "Razón: Problemas Familiares": "Reason: Family Problems",
  "Razón: Por Trabajo": "Reason: Work",
  "Docentes SEDUC - Prebásica": "Ministry Teachers – Pre-primary",
  "Docentes SEDUC - Básica": "Ministry Teachers – Basic",
  "Docentes SEDUC - Media": "Ministry Teachers – Secondary",
  "Docentes SEDUC - Total": "Ministry Teachers – Total",
  "Docentes Superior - Femenino": "Higher-Ed Teachers – Female",
  "Docentes Superior - Masculino": "Higher-Ed Teachers – Male",
  "Docentes Superior - Total": "Higher-Ed Teachers – Total",
  "Estudiantes Superior - Público": "Higher-Ed Students – Public",
  "Estudiantes Superior - Privado": "Higher-Ed Students – Private",
  "Estudiantes Superior - Total": "Higher-Ed Students – Total",
  "Textos Escolares": "Textbooks",
  "Presupuesto - % del PIB": "Budget – % of GDP",
  "Presupuesto - % del PGR": "Budget – % of National Budget",
  "Presupuesto Vigente": "Current Budget",
  "Matrícula por Nivel": "Enrolment by Level",
  "Cobertura por Nivel": "Coverage by Level",
  "Enrolamiento por Nivel": "Enrolment by Level",
  "Años de Estudio por Género": "Years of Schooling by Gender",
  "Analfabetismo por Género": "Illiteracy by Gender",
  "Analfabetismo por Quintil": "Illiteracy by Quintile",
  "Repitencia por Nivel": "Repetition by Level",
  "Reprobación por Nivel": "Failure by Level",
  "Matemáticas por Grado": "Mathematics by Grade",
  "Graduados por Nivel": "Graduates by Level",
  "Alumnos por Maestro": "Pupils per Teacher",
  "Razones de No Estudio": "Reasons for Non-Attendance",
  "Docentes SEDUC por Nivel": "Ministry Teachers by Level",
  "Docentes Superior por Género": "Higher-Ed Teachers by Gender",
  "Estudiantes Superior": "Higher-Ed Students",
  "Presupuesto Educación": "Education Budget",
  "Textos por Tipo": "Textbooks by Type",
  "Gasto Ejecutado por Nivel": "Executed Spending by Level",
  "Presupuesto Ejecutado por Objeto": "Executed Budget by Category",
  "Gasto Vigente por Nivel": "Current Spending by Level",
  "Presupuesto Vigente por Objeto": "Current Budget by Category",
  "% Ejecución Presupuestaria": "% Budget Execution",

  /* --- Denominaciones --- */
  "Cantidad": "Count",
  "Porcentaje": "Percentage",
  "Lempiras": "Lempiras",
  "Cantidad de estudiantes": "Number of students",
  "Porcentaje (%)": "Percentage (%)",
  "Años de estudio": "Years of schooling",
  "Cantidad de graduados": "Number of graduates",
  "Cantidad de alumnos": "Number of pupils",
  "Número de docentes": "Number of teachers",
  "Número de estudiantes": "Number of students",
  "Millones de Lempiras": "Millions of Lempiras",

  /* --- Series --- */
  "Prebásica": "Pre-primary",
  "Básica": "Basic",
  "Media": "Secondary",
  "Total": "Total",
  "Hombres": "Men",
  "Mujeres": "Women",
  "Q1 (más pobre)": "Q1 (poorest)",
  "Q2": "Q2",
  "Q3": "Q3",
  "Q4": "Q4",
  "Q5 (más rico)": "Q5 (richest)",
  "3er Grado": "Grade 3",
  "6to Grado": "Grade 6",
  "9no Grado": "Grade 9",
  "12vo Grado": "Grade 12",
  "Falta de recursos": "Lack of resources",
  "No quiere": "Does not wish to continue",
  "Problemas fam./salud": "Family/health problems",
  "Por trabajo": "Work",
  "Femenino": "Female",
  "Masculino": "Male",
  "Público": "Public",
  "Privado": "Private",
  "% del PIB": "% of GDP",
  "% del PGR": "% of national budget",
  "Estudiante": "Student",
  "Docente": "Teacher",
  "Trabajo": "Administrative staff",
  "Servicios Personales": "Personnel services",
  "Transferencias y Donaciones": "Transfers and grants",
  "Servicios No Personales": "Non-personnel services",
  "Materiales y suministros": "Materials and supplies",
  "Bienes capitalizables": "Capital goods",

  /* --- Descripciones --- */
  "Cantidad de estudiantes matriculados en el nivel prebásico.": "Number of students enrolled at the pre-primary level.",
  "Cantidad de estudiantes matriculados en el nivel básico.": "Number of students enrolled at the basic level.",
  "Cantidad de estudiantes matriculados en el nivel medio.": "Number of students enrolled at the secondary level.",
  "Cantidad total de estudiantes matriculados en el sistema educativo.": "Total number of students enrolled in the education system.",
  "Porcentaje de niños en edad de cursar el nivel prebásico que están matriculados.": "Share of children of pre-primary age who are enrolled.",
  "Porcentaje de niños en edad de cursar el nivel básico que están matriculados.": "Share of children of basic-education age who are enrolled.",
  "Porcentaje de jóvenes en edad de cursar el nivel medio que están matriculados.": "Share of young people of secondary-education age who are enrolled.",
  "Porcentaje total de cobertura educativa bruta a nivel nacional.": "Total gross education coverage rate nationwide.",
  "Cantidad de niños y jóvenes en edad escolar que no están matriculados en el sistema educativo.": "Number of school-age children and young people not enrolled in the education system.",
  "Porcentaje de estudiantes de prebásica matriculados en centros educativos privados.": "Share of pre-primary students enrolled in private schools.",
  "Porcentaje de estudiantes de básica matriculados en centros educativos privados.": "Share of basic-education students enrolled in private schools.",
  "Porcentaje de estudiantes de media matriculados en centros educativos privados.": "Share of secondary students enrolled in private schools.",
  "Porcentaje total de estudiantes matriculados en centros educativos privados.": "Total share of students enrolled in private schools.",
  "Años promedio de escolaridad alcanzados por los hombres en Honduras.": "Average years of schooling attained by men in Honduras.",
  "Años promedio de escolaridad alcanzados por las mujeres en Honduras.": "Average years of schooling attained by women in Honduras.",
  "Años promedio de escolaridad alcanzados por la población hondureña.": "Average years of schooling attained by the Honduran population.",
  "Porcentaje de hombres que no saben leer ni escribir.": "Share of men who cannot read or write.",
  "Porcentaje de mujeres que no saben leer ni escribir.": "Share of women who cannot read or write.",
  "Porcentaje de la población total que no sabe leer ni escribir.": "Share of the total population who cannot read or write.",
  "Porcentaje de analfabetismo en el quintil de ingresos más bajo de la población.": "Illiteracy rate in the lowest income quintile of the population.",
  "Porcentaje de analfabetismo en el segundo quintil de ingresos de la población.": "Illiteracy rate in the second income quintile of the population.",
  "Porcentaje de analfabetismo en el tercer quintil de ingresos de la población.": "Illiteracy rate in the third income quintile of the population.",
  "Porcentaje de analfabetismo en el cuarto quintil de ingresos de la población.": "Illiteracy rate in the fourth income quintile of the population.",
  "Porcentaje de analfabetismo en el quintil de ingresos más alto de la población.": "Illiteracy rate in the highest income quintile of the population.",
  "Porcentaje de estudiantes de básica que repiten el grado que cursan.": "Share of basic-education students repeating their current grade.",
  "Porcentaje de estudiantes de media que repiten el grado que cursan.": "Share of secondary students repeating their current grade.",
  "Porcentaje total de estudiantes que repiten el grado que cursan.": "Total share of students repeating their current grade.",
  "Porcentaje de estudiantes de prebásica que reprueban el grado que cursan.": "Share of pre-primary students failing their current grade.",
  "Porcentaje de estudiantes de básica que reprueban el grado que cursan.": "Share of basic-education students failing their current grade.",
  "Porcentaje de estudiantes de media que reprueban el grado que cursan.": "Share of secondary students failing their current grade.",
  "Porcentaje total de estudiantes que reprueban el grado que cursan.": "Total share of students failing their current grade.",
  "Porcentaje de estudiantes de tercer grado según su nivel de desempeño en matemáticas.": "Share of grade 3 students by mathematics performance level.",
  "Porcentaje de estudiantes de sexto grado según su nivel de desempeño en matemáticas.": "Share of grade 6 students by mathematics performance level.",
  "Porcentaje de estudiantes de noveno grado según su nivel de desempeño en matemáticas.": "Share of grade 9 students by mathematics performance level.",
  "Cantidad histórica de estudiantes graduados de noveno grado.": "Historical number of students graduating from grade 9.",
  "Cantidad histórica de estudiantes graduados de duodécimo grado.": "Historical number of students graduating from grade 12.",
  "Cantidad histórica total de estudiantes graduados de básica y media.": "Total historical number of students graduating from basic and secondary education.",
  "Promedio de alumnos por cada maestro en el nivel prebásico.": "Average number of pupils per teacher at the pre-primary level.",
  "Promedio de alumnos por cada maestro en el nivel básico.": "Average number of pupils per teacher at the basic level.",
  "Promedio total de alumnos por cada maestro en el sistema educativo.": "Overall average number of pupils per teacher in the education system.",
  "Porcentaje de estudiantes de prebásica cubiertos por el programa de merienda escolar.": "Share of pre-primary students covered by the school meal programme.",
  "Porcentaje de estudiantes de básica cubiertos por el programa de merienda escolar.": "Share of basic-education students covered by the school meal programme.",
  "Porcentaje total de estudiantes cubiertos por el programa de merienda escolar.": "Total share of students covered by the school meal programme.",
  "Porcentaje de menores entre 6 y 17 años que no estudian por falta de recursos económicos.": "Share of children aged 6–17 not attending school owing to a lack of financial resources.",
  "Porcentaje de menores entre 6 y 17 años que no estudian porque no quieren seguir estudiando.": "Share of children aged 6–17 not attending school because they do not wish to continue studying.",
  "Porcentaje de menores entre 6 y 17 años que no estudian por problemas familiares o de salud.": "Share of children aged 6–17 not attending school owing to family or health problems.",
  "Porcentaje de menores entre 6 y 17 años que no estudian porque deben trabajar.": "Share of children aged 6–17 not attending school because they must work.",
  "Cantidad de docentes de la Secretaría de Educación asignados al nivel prebásico.": "Number of Ministry of Education teachers assigned to the pre-primary level.",
  "Cantidad de docentes de la Secretaría de Educación asignados al nivel básico.": "Number of Ministry of Education teachers assigned to the basic level.",
  "Cantidad de docentes de la Secretaría de Educación asignados al nivel medio.": "Number of Ministry of Education teachers assigned to the secondary level.",
  "Cantidad total de docentes de la Secretaría de Educación.": "Total number of Ministry of Education teachers.",
  "Cantidad de docentes mujeres en el nivel de educación superior.": "Number of female teaching staff in higher education.",
  "Cantidad de docentes hombres en el nivel de educación superior.": "Number of male teaching staff in higher education.",
  "Cantidad total de docentes en el nivel de educación superior.": "Total number of teaching staff in higher education.",
  "Cantidad de estudiantes matriculados en universidades públicas.": "Number of students enrolled in public universities.",
  "Cantidad de estudiantes matriculados en universidades privadas.": "Number of students enrolled in private universities.",
  "Cantidad total de estudiantes matriculados en educación superior.": "Total number of students enrolled in higher education.",
  "Cantidad total de textos escolares entregados a nivel nacional.": "Total number of school textbooks delivered nationwide.",
  "Porcentaje del Producto Interno Bruto (PIB) destinado a la educación.": "Share of Gross Domestic Product (GDP) allocated to education.",
  "Porcentaje del Presupuesto General de la República destinado a la educación.": "Share of the General Budget of the Republic allocated to education.",
  "Presupuesto vigente asignado al sector educativo.": "Current budget allocated to the education sector.",
  "Cantidad de estudiantes matriculados en el sistema educativo, comparando los distintos niveles (prebásica, básica, media y total).": "Number of students enrolled in the education system, comparing levels (pre-primary, basic, secondary, and total).",
  "Porcentaje de cobertura educativa bruta, comparando los distintos niveles del sistema educativo.": "Gross education coverage rate, comparing levels of the education system.",
  "Porcentaje de estudiantes matriculados en centros educativos privados, comparando los distintos niveles.": "Share of students enrolled in private schools, comparing levels.",
  "Años promedio de escolaridad, comparando hombres, mujeres y el total de la población.": "Average years of schooling, comparing men, women, and the total population.",
  "Porcentaje de analfabetismo, comparando hombres, mujeres y el total de la población.": "Illiteracy rate, comparing men, women, and the total population.",
  "Porcentaje de analfabetismo según el quintil de ingresos de la población.": "Illiteracy rate by income quintile of the population.",
  "Porcentaje de estudiantes que repiten el grado que cursan, comparando los distintos niveles educativos.": "Share of students repeating their current grade, comparing education levels.",
  "Porcentaje de estudiantes que reprueban el grado que cursan, comparando los distintos niveles educativos.": "Share of students failing their current grade, comparing education levels.",
  "Nivel de desempeño en matemáticas de los estudiantes, comparando los distintos grados evaluados.": "Students' mathematics performance level, comparing the grades assessed.",
  "Cantidad histórica de estudiantes graduados, comparando noveno grado, duodécimo grado y el total.": "Historical number of graduating students, comparing grade 9, grade 12, and the total.",
  "Promedio de alumnos por maestro, comparando los distintos niveles educativos.": "Average pupils per teacher, comparing education levels.",
  "Razones principales por las cuales los menores entre 6 y 17 años no están estudiando.": "Main reasons children aged 6–17 are not attending school.",
  "Cantidad de docentes de la Secretaría de Educación, comparando los distintos niveles.": "Number of Ministry of Education teachers, comparing levels.",
  "Cantidad de docentes en educación superior, comparando hombres y mujeres.": "Number of higher education teaching staff, comparing men and women.",
  "Cantidad de estudiantes en educación superior, comparando universidades públicas y privadas.": "Number of higher education students, comparing public and private universities.",
  "Presupuesto asignado al sector educativo, comparando su relación con el PIB, el Presupuesto General y el monto vigente.": "Budget allocated to the education sector, comparing its relationship to GDP, the General Budget, and the current amount.",
  "Cantidad de textos escolares entregados, desagregada por tipo de beneficiario (estudiante, docente o personal administrativo).": "Number of school textbooks delivered, disaggregated by recipient type (student, teacher, or administrative staff).",
  "Gasto gubernamental efectivamente ejecutado, comparando los distintos niveles del sistema educativo.": "Government spending actually executed, comparing levels of the education system.",
  "Presupuesto efectivamente ejecutado por la Secretaría de Educación, desagregado por objeto o categoría de gasto.": "Budget actually executed by the Ministry of Education, disaggregated by expenditure category.",
  "Gasto gubernamental vigente (planificado), comparando los distintos niveles del sistema educativo.": "Current (planned) government spending, comparing levels of the education system.",
  "Presupuesto vigente (planificado) de la Secretaría de Educación, desagregado por objeto o categoría de gasto.": "Current (planned) Ministry of Education budget, disaggregated by expenditure category.",
  "Porcentaje de ejecución del presupuesto de la Secretaría de Educación, desagregado por objeto o categoría de gasto.": "Budget execution rate of the Ministry of Education, disaggregated by expenditure category.",

  /* --- Fuentes --- */
  "Elaboracion propia con datos obtenidos de la Secretaría de Educación": "Own elaboration using data from the Ministry of Education",
  "Elaboracion propia con datos obtenidos del Instituto Nacional de Estadisticas": "Own elaboration using data from the National Institute of Statistics",
  "Elaboracion propia con datos obtenidos del  Banco Central de Honduras y Honduras en cifras": "Own elaboration using data from the Central Bank of Honduras and Honduras en Cifras",
  "Elaboracion propia con datos obtenidos de la Universidad Nacional Autónoma de Honduras": "Own elaboration using data from the National Autonomous University of Honduras",
  "Elaboracion propia con datos obtenidos de Red Solidaria": "Own elaboration using data from Red Solidaria",
  "Elaboración propia con datos del Banco Central de Honduras y la Secretaría de Finanzas": "Own elaboration using data from the Central Bank of Honduras and the Ministry of Finance",
  "Elaboración propia con datos de la Secretaría de Finanzas": "Own elaboration using data from the Ministry of Finance",
  "Secretaría de Educación": "Ministry of Education",
  "Instituto Nacional de Estadísticas": "National Institute of Statistics",
  "BCH, Honduras en Cifras": "Central Bank of Honduras, Honduras en Cifras",
  "UNAH": "UNAH (National Autonomous University of Honduras)",
  "Elaboración propia con datos del BCH y SEFIN": "Own elaboration using data from the Central Bank of Honduras and SEFIN",
  "Elaboración propia con datos obtenidos de la Secretaría de Educación": "Own elaboration using data from the Ministry of Education"
});

window.PAGE_TITLE = {es: "Educación — Estado del País Honduras 2026", en: "Education — State of the Nation Honduras 2026"};