window.DICT_SECTOR = Object.assign(window.DICT_SECTOR || {}, {

  /* --- Correcciones y nombres nuevos (lote 2026) --- */
  "Elaboración propia con datos obtenidos de World Health Organization": "Own elaboration using data from the World Health Organization",
  "Elaboración propia con datos obtenidos mediante la Food and Agriculture organization of the United Nations": "Own elaboration using data from the Food and Agriculture Organization of the United Nations",
  "Elaboración Propia mediante datos obtenidos de la Organizacion Panamericana de la Salud": "Own elaboration using data from the Pan American Health Organization",
  "Elaboración propia mediante informacion obtenida de la Secretaria de Salud y el  Instituto Nacional de Estadisticas (2011-2023)": "Own elaboration using information from the Ministry of Health and the National Institute of Statistics (2011–2023)",
  "Elaboración propia mediante datos obtenidos de la Secretaria de Salud": "Own elaboration using data from the Ministry of Health",

  /* --- Sector --- */
  "Salud": "Health",

  /* --- Secciones --- */
  "IMPACTO HUMANO": "HUMAN IMPACT",
  "CALIDAD": "QUALITY",
  "GOBERNANZA Y RECURSOS": "GOVERNANCE AND RESOURCES",
  "COVID-19": "COVID-19",

  /* --- Series y desagregaciones --- */
  "Nivel I": "Level I",
  "Nivel II": "Level II",
  "Presupuesto asignado": "Allocated budget",
  "Presupuesto ejecutado": "Executed budget",

  /* --- Países (comparativo) --- */
  "Guatemala": "Guatemala",
  "Honduras": "Honduras",
  "Costa Rica": "Costa Rica",
  "Nicaragua": "Nicaragua",
  "El Salvador": "El Salvador",

  /* --- Causas de muerte --- */
  "Interpersonal violence": "Interpersonal violence",
  "Ischaemic heart disease": "Ischaemic heart disease",
  "Stroke": "Stroke",
  "Chronic obstructive pulmonary disease": "Chronic obstructive pulmonary disease",
  "Road injury": "Road injury",
  "Cirrhosis of the liver": "Cirrhosis of the liver",
  "Lower respiratory infections": "Lower respiratory infections",
  "Diabetes mellitus": "Diabetes mellitus",
  "Hypertensive heart disease": "Hypertensive heart disease",

  /* --- Denominaciones --- */
  "Número de Casos de Dengue": "Number of Dengue Cases",
  "Número de Atenciones en Establecimientos de la Sesal (Primer Nivel)": "Number of Consultations in Ministry of Health Facilities (First Level)",
  "Número de Establecimientos de Salud de la Sesal": "Number of Ministry of Health Facilities",
  "Años": "Years",
  "% adultos (+18 años)": "% of adults (18+)",
  "% de la población": "% of population",
  "Número de casos": "Number of cases",
  "Por 100,000 nacidos vivos": "Per 100,000 live births",
  "Por cada 1,000 nacidos vivos": "Per 1,000 live births",
  "Por cada 1,000 mujeres": "Per 1,000 women",
  "Tasa por 100,000 hab.": "Rate per 100,000 inhabitants",
  "Por 1,000 mujeres (15-19 años)": "Per 1,000 women (aged 15–19)",
  "% del gasto total en salud": "% of total health expenditure",
  "Por 1,000 habitantes": "Per 1,000 inhabitants",
  "Número de atenciones": "Number of consultations",
  "Porcentaje (%)": "Percentage (%)",
  "Por cada 1,000 personas": "Per 1,000 people",
  "Número de establecimientos": "Number of facilities",
  "Porcentaje del PIB (%)": "Share of GDP (%)",
  "Miles de millones de Lempiras": "Billions of Lempiras",
  "Millones de Lempiras": "Millions of Lempiras",
  "Por cada 100,000 nacidos vivos": "Per 100,000 live births",
  "Porcentaje de la población adulta (18 años o más) con sobrepeso u obesidad.": "Share of the adult population (18 or older) who are overweight or obese.",
  "Porcentaje de la población hondureña que sufre de desnutrición.": "Share of the Honduran population that is undernourished.",
  "Porcentaje de la población con acceso a un sistema de saneamiento mejorado (letrinas o alcantarillado adecuado).": "Share of the population with access to an improved sanitation system (adequate latrines or sewerage).",
  "Porcentaje de la población del área rural con acceso a una fuente de agua mejorada.": "Share of the rural population with access to an improved water source.",
  "Porcentaje de la población del área urbana con acceso a una fuente de agua mejorada.": "Share of the urban population with access to an improved water source.",
  "Porcentaje total de la población con acceso a una fuente de agua mejorada, a nivel nacional.": "Total share of the population with access to an improved water source, nationwide.",
  "Porcentaje del gasto en salud que las personas pagan directamente de su bolsillo, sin cobertura de seguro.": "Share of health spending that people pay directly out of pocket, without insurance coverage.",
  "Porcentaje de la población infantil vacunada contra la poliomielitis.": "Share of the child population vaccinated against poliomyelitis.",
  "Porcentaje del Producto Interno Bruto (PIB) que el gobierno destina al sector salud.": "Share of Gross Domestic Product (GDP) that the government allocates to the health sector.",

  /* --- Fuentes --- */
  "Health Data Overview Honduras WHO": "Health Data Overview Honduras, WHO",
  "Elaboracion propia con datos obtenidos de World Health Organization": "Own elaboration using data from the World Health Organization",
  "Elaboracion propia con datos obtenidos mediante la Food and Agriculture organization of the United Nations": "Own elaboration using data from the Food and Agriculture Organization of the United Nations",
  "Elaboración propia con datos obtendios del Instituto Nacional de Estadísticas (2012-2022)": "Own elaboration using data from the National Institute of Statistics (2012–2022)",
  "Elaboración propia con datos de la Secretaría de Salud (2012-2022)": "Own elaboration using data from the Ministry of Health (2012–2022)",
  "Elaboración propia mediante datos obtenidos en el área estadística de la Secretaría de Salud y la Organización Panamericana de la Salud (OPS)": "Own elaboration using data from the statistics unit of the Ministry of Health and the Pan American Health Organization (PAHO)",
  "Elaboración propia mediante datos obtenidos en el area estadistica de la Secretaria de Salud": "Own elaboration using data from the statistics unit of the Ministry of Health",
  "Elaboración propia mediante datos obtenidos de World Bank Data": "Own elaboration using World Bank data",
  "Elaboración propia mediante datos obtenidos en el Health Data Overview Honduras WHO": "Own elaboration using data from the Health Data Overview Honduras, WHO",
  "Elaboración propia mediante informacion obtenida de la secreatria de salud, Instituto Nacional de estadisticas y la Organizacion Panamericana de la Salud": "Own elaboration using information from the Ministry of Health, the National Institute of Statistics, and the Pan American Health Organization",
  "Elaboración propia mediante datos obtenidos de World data Bank": "Own elaboration using World Bank data",
  "Elaboración propia mediante datos obtenidos del Banco Mundial y la Organizacion Panamericana de la Salud": "Own elaboration using data from the World Bank and the Pan American Health Organization",
  "Elaboración propia con datos de la Secretaría de Salud correspondientes al período 2010–2023. Los datos de 2024 fueron obtenidos mediante solicitud de información pública No. SOL-SDS-4847-2025": "Own elaboration using Ministry of Health data for the period 2010–2023. The 2024 data were obtained through public information request No. SOL-SDS-4847-2025",
  "Elaboracion Propia mediante datos obtenidos de la Organizacion Panamericana de la Salud": "Own elaboration using data from the Pan American Health Organization",
  "Elaboracion propia mediante informacion obtenida de la Secretaria de Salud y el  Instituto Nacional de Estadisticas (2011-2023)": "Own elaboration using information from the Ministry of Health and the National Institute of Statistics (2011–2023)",
  "Elaboracion propia mediante datos obtenidos de la Secretaria de Salud": "Own elaboration using data from the Ministry of Health",
  "Elaboración propia mediante datos obtenidos de la Secretaría de Finanzas y el Banco Central de Honduras": "Own elaboration using data from the Ministry of Finance and the Central Bank of Honduras",
  "Elaboración propia mediante datos obtenidos de la Secretaría de Finanzas": "Own elaboration using data from the Ministry of Finance",
  "Fuente: Elaboración propia con datos obtenidos de los reportes de ejecución del gasto de la Secretaría de Finanzas del 2022 a octubre del 2025.": "Source: Own elaboration using data from the Ministry of Finance expenditure execution reports, 2022 to October 2025.",
  "Organización Panamericana de la Salud (OPS), Tablero de Indicadores Básicos. https://opendata.paho.org/es/indicadores-basicos/tablero-de-los-indicadores-basicos": "Pan American Health Organization (PAHO), Core Indicators Dashboard. https://opendata.paho.org/es/indicadores-basicos/tablero-de-los-indicadores-basicos",

  /* --- Descripciones --- */
  "Presupuesto total de salud": "Total Health Budget",
  "Número promedio de años que se espera viva una persona en Honduras, desagregado por sexo.": "Average number of years a person in Honduras is expected to live, disaggregated by sex.",
  "Cantidad de casos de dengue registrados a nivel nacional por año.": "Number of dengue cases recorded nationwide per year.",
  "Cantidad de muertes maternas registradas por cada 100,000 nacidos vivos.": "Number of maternal deaths recorded per 100,000 live births.",
  "Cantidad de muertes de menores de un año registradas por cada 1,000 nacidos vivos.": "Number of deaths of children under one year recorded per 1,000 live births.",
  "Cantidad de muertes de mujeres registradas por cada 1,000 mujeres.": "Number of female deaths recorded per 1,000 women.",
  "Principales enfermedades y causas que provocan la mayor cantidad de muertes en Honduras.": "Leading diseases and causes accounting for the greatest number of deaths in Honduras.",
  "Cantidad de nacimientos registrados en mujeres adolescentes de 15 a 19 años, por cada 1,000 mujeres de ese rango de edad.": "Number of births recorded among adolescent women aged 15–19, per 1,000 women in that age range.",
  "Cantidad de atenciones médicas brindadas en los establecimientos de primer nivel de la Secretaría de Salud (Sesal).": "Number of medical consultations provided in first-level facilities of the Ministry of Health (Sesal).",
  "Cantidad de camas hospitalarias disponibles por cada 1,000 personas.": "Number of hospital beds available per 1,000 people.",
  "Cantidad de establecimientos de salud operados por la Secretaría de Salud (Sesal) a nivel nacional.": "Number of health facilities operated by the Ministry of Health (Sesal) nationwide.",
  "Presupuesto total asignado al sector salud por año.": "Total budget allocated to the health sector per year.",
  "Presupuesto específico destinado a la compra de medicamentos.": "Dedicated budget for the purchase of medicines.",
  "Comparación de la razón de mortalidad materna entre Honduras y otros países de Centroamérica.": "Comparison of the maternal mortality ratio between Honduras and other Central American countries.",

  /* --- Indicadores y etiquetas de la barra lateral --- */
  "Esperanza de Vida": "Life Expectancy",
  "Prevalencia de Sobrepeso u Obesidad": "Prevalence of Overweight or Obesity",
  "Prevalencia de Sobrepeso": "Overweight Prevalence",
  "Prevalencia de Desnutricion (% de Poblacion)": "Prevalence of Undernourishment (% of Population)",
  "Desnutrición": "Undernourishment",
  "Acceso a saneamiento mejorado (proporción de la población)": "Access to Improved Sanitation (share of population)",
  "Saneamiento": "Sanitation",
  "Acceso a una fuente de agua mejorada (proporción de la población) - Rural": "Access to an Improved Water Source (share of population) – Rural",
  "Agua Mejorada - Rural": "Improved Water – Rural",
  "Acceso a una fuente de agua mejorada (proporción de la población) - Urbano": "Access to an Improved Water Source (share of population) – Urban",
  "Agua Mejorada - Urbano": "Improved Water – Urban",
  "Acceso a una fuente de agua mejorada (proporción de la población) - TOTAL": "Access to an Improved Water Source (share of population) – TOTAL",
  "Agua Mejorada - Total": "Improved Water – Total",
  "Razón de Mortalidad materna por cada 100,000 nacidos vivos": "Maternal Mortality Ratio per 100,000 Live Births",
  "Mortalidad Materna": "Maternal Mortality",
  "Mortalidad infantil por cada 1,000 nacidos vivos": "Infant Mortality per 1,000 Live Births",
  "Mortalidad Infantil": "Infant Mortality",
  "Mortalidad en mujeres por cada 1000 mujeres": "Female Mortality per 1,000 Women",
  "Mortalidad en Mujeres": "Female Mortality",
  "Principales Causas de Muerte": "Leading Causes of Death",
  "Tasa de Fecundidad de las Adolescentes (nacimientos por cada 1,000 mujeres de 15 a 19 años)": "Adolescent Fertility Rate (births per 1,000 women aged 15–19)",
  "Fecundidad Adolescente": "Adolescent Fertility",
  "Gasto de Bolsillo en Salud": "Out-of-Pocket Health Expenditure",
  "Tasa de muertes a nivel general (por 1,000 habitantes)": "Crude Death Rate (per 1,000 inhabitants)",
  "Tasa de Muertes General": "Crude Death Rate",
  "Atenciones Nivel 1": "Level 1 Consultations",
  "Cobertura en Vacunación de Polio": "Polio Vaccination Coverage",
  "Cobertura de Vacuna": "Vaccination Coverage",
  "Tasa de camas hospitalarias (por cada 1,000 personas)": "Hospital Bed Rate (per 1,000 people)",
  "Camas": "Hospital Beds",
  "Establecimientos": "Health Facilities",
  "Gasto del gobierno en salud como porcentaje del PIB": "Government Health Expenditure as a Share of GDP",
  "Gasto en Salud (% PIB)": "Health Expenditure (% of GDP)",
  "Presupuesto Total": "Total Budget",
  "Presupuesto Especifico para medicamentos (Millones de Lempiras)": "Dedicated Budget for Medicines (Millions of Lempiras)",
  "Presupuesto Medicamentos": "Medicines Budget",
  "Razón de Mortalidad Materna – Comparativo Centroamérica": "Maternal Mortality Ratio – Central America Comparison",
  "Mortalidad Materna (Centroamérica)": "Maternal Mortality (Central America)",
  "Cantidad total de muertes registradas a nivel nacional por cada 1,000 habitantes.": "Total number of deaths recorded nationwide per 1,000 inhabitants.",
});

window.PAGE_TITLE = {es: "Salud \u2014 Estado del Pa\u00eds Honduras 2026", en: "Health \u2014 State of the Nation Honduras 2026"};