/* DICCIONARIO DEL SECTOR: SECTOR ELECTRICO */

window.DICT_SECTOR = Object.assign(window.DICT_SECTOR || {}, {

  /* --- Correcciones y nombres nuevos (lote 2026) --- */
  "Frecuencia media de interrupción por usuario (SAIFI)": "Average Interruption Frequency per User (SAIFI)",
  "Tiempo Promedio de Interrupciones en el Servicio de Energía Eléctrica (SAIDI)": "Average Duration of Electricity Service Interruptions (SAIDI)",
  /* --- Mapas y textos adicionales --- */
  "Año:": "Year:",
  "Pasá el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",
  "Pasa el mouse sobre el mapa para ver los datos de cada departamento.": "Hover over the map to see the data for each department.",

  /* --- Sector --- */
  "Sector Eléctrico": "Electricity Sector",

  /* --- Secciones --- */
  "TARIFAS Y COSTOS": "TARIFFS AND COSTS",
  "FINANZAS Y DEUDA": "FINANCE AND DEBT",
  "CONFIABILIDAD DEL SERVICIO": "SERVICE RELIABILITY",
  "GENERACIÓN Y COBERTURA": "GENERATION AND COVERAGE",

  /* --- Nombres de indicadores --- */
  "Tarifa Eléctrica Promedio por Categoría de Servicio": "Average Electricity Tariff by Service Category",
  "Ejecución presupuestaria de la Empresa Nacional de Energía Eléctrica": "Budget Execution of the National Electric Power Company (ENEE)",
  "Presupuesto de la Empresa Nacional de Energía Eléctrica": "Budget of the National Electric Power Company (ENEE)",
  "Pérdidas de Energía en Distribución": "Energy Losses in Distribution",
  "Costo de Generación de Energía": "Cost of Energy Generation",
  "Energía Generada por Tipo de Tecnología": "Energy Generated by Technology Type",
  "Deuda Interna de la ENEE": "Domestic Debt of ENEE",
  "Deuda Externa de la ENEE": "External Debt of ENEE",
  "Número de Empresas Participantes en el Mercado Eléctrico Nacional": "Number of Companies Participating in the National Electricity Market",
  "Tarifa Promedio Anual": "Average Annual Tariff",
  "Energia generada": "Energy Generated",
  "Índice de Cobertura Eléctrica por Departamento": "Electricity Coverage Index by Department",
  "Energia No Suministrada (MWh)": "Energy Not Supplied (MWh)",
  "Frecuencia media de interrupción por usuario": "Average Interruption Frequency per User (SAIFI)",
  "Tiempo Promedio de Interrupciones en el Servicio de Energía Eléctrica": "Average Duration of Electricity Service Interruptions (SAIDI)",

  /* --- Etiquetas de la barra lateral --- */
  "Tarifa por Servicio": "Tariff by Service",
  "Ejecución Presupuestaria": "Budget Execution",
  "Presupuesto de la ENEE": "ENEE Budget",
  "Pérdida de Energía": "Energy Losses",
  "Costo de Generación Energia": "Generation Cost",
  "Energía por Tipo de Tecnología": "Energy by Technology",
  "Deuda Interna": "Domestic Debt",
  "Deuda Externa": "External Debt",
  "Empresas Mercado Electrico": "Electricity Market Companies",
  "Energía Generada": "Energy Generated",
  "Índice de Cobertura Eléctrica": "Electricity Coverage Index",
  "Energía no Suministrada": "Energy Not Supplied",
  "SAIFI": "SAIFI",
  "SAIDI": "SAIDI",

  /* --- Denominaciones --- */
  "Lempiras por kWh": "Lempiras per kWh",
  "Porcentaje (%)": "Percentage (%)",
  "Lempiras": "Lempiras",
  "Millones de Lempiras": "Millions of Lempiras",
  "MWh": "MWh",
  "Millones de USD": "Millions of USD",
  "Número de empresas": "Number of companies",
  "GWh": "GWh",
  "Interrupciones por usuario": "Interruptions per user",
  "Horas por usuario": "Hours per user",

  /* --- Series --- */
  "Promedio de Alta Tensión": "High voltage (average)",
  "Promedio de Baja Tensión": "Low voltage (average)",
  "Promedio de Media Tensión": "Medium voltage (average)",
  "Promedio de Residencial (mayor a 50 kWh)": "Residential, above 50 kWh (average)",
  "Promedio de Residencial (menor a 50 kWh)": "Residential, below 50 kWh (average)",
  "Aprobado": "Approved",
  "Devengado": "Accrued",
  "Biomasa": "Biomass",
  "Eólica": "Wind",
  "Geotermia": "Geothermal",
  "Hidroeléctrica": "Hydroelectric",
  "Solar": "Solar",
  "Térmica": "Thermal",
  "Administración Central": "Central government",
  "Fideicomiso de la Tasa de Seguridad": "Security Tax Trust Fund",
  "Institutos de Previsión Públicos": "Public pension institutes",
  "Sector Financiero Privado": "Private financial sector",
  "Bancos Comerciales": "Commercial banks",
  "Bilateral": "Bilateral",
  "Multilateral": "Multilateral",
  "No Renovable (GWh)": "Non-renewable (GWh)",
  "Renovable (GWh)": "Renewable (GWh)",
  "ENS por fallas": "Energy not supplied \u2013 faults",
  "ENS por mantenimiento": "Energy not supplied \u2013 maintenance",

  /* --- Categorias del eje X --- */
  "Empresas Generadoras con equipos de Cogeneración": "Generators with cogeneration equipment",
  "Empresas Comercializadoras": "Retail suppliers",
  "Empresas Generadoras": "Generation companies",
  "Empresas Transmisoras": "Transmission companies",
  "Islas de la Bahía": "Bay Islands",

  /* --- Descripciones --- */
  "Tarifa promedio pagada por los consumidores según su categoría de servicio eléctrico: alta, media y baja tensión, y residencial según nivel de consumo.": "Average tariff paid by consumers according to their electricity service category: high, medium, and low voltage, and residential by level of consumption.",
  "Porcentaje de ejecución del presupuesto asignado a la Empresa Nacional de Energía Eléctrica (ENEE) por año.": "Share of the budget allocated to the National Electric Power Company (ENEE) that was executed, by year.",
  "Presupuesto aprobado y devengado de la Empresa Nacional de Energía Eléctrica (ENEE) por año.": "Approved and accrued budget of the National Electric Power Company (ENEE), by year.",
  "Pérdidas económicas de la ENEE asociadas a energía no facturada durante el proceso de distribución.": "Financial losses incurred by ENEE from unbilled energy during the distribution process.",
  "Costo de generación de energía eléctrica según el tipo de tecnología utilizada: biomasa, eólica, geotermia, hidroeléctrica, solar y térmica.": "Cost of electricity generation by technology type: biomass, wind, geothermal, hydroelectric, solar, and thermal.",
  "Cantidad de energía eléctrica generada según el tipo de tecnología utilizada.": "Amount of electricity generated by technology type.",
  "Deuda interna de la ENEE desagregada por tipo de acreedor: administración central, fideicomisos, institutos y sector financiero privado.": "Domestic debt of ENEE disaggregated by creditor type: central government, trust funds, pension institutes, and the private financial sector.",
  "Deuda externa de la ENEE desagregada por tipo de acreedor: bancos comerciales, bilateral y multilateral.": "External debt of ENEE disaggregated by creditor type: commercial banks, bilateral, and multilateral.",
  "Número de empresas que participan en el mercado eléctrico nacional, según su categoría de participación.": "Number of companies participating in the national electricity market, by category of participation.",
  "Tarifa eléctrica promedio anual cobrada a nivel nacional.": "Average annual electricity tariff charged nationwide.",
  "Energía eléctrica generada en Honduras, comparando fuentes renovables y no renovables.": "Electricity generated in Honduras, comparing renewable and non-renewable sources.",
  "Porcentaje de cobertura del servicio eléctrico por departamento.": "Share of electricity service coverage by department.",
  "Energía eléctrica no suministrada a los usuarios debido a fallas o a labores de mantenimiento del sistema.": "Electricity not supplied to users owing to system faults or maintenance work.",
  "Frecuencia promedio con la que un usuario experimenta interrupciones en el servicio eléctrico durante el año.": "Average frequency with which a user experiences interruptions to electricity service over the year.",
  "Tiempo promedio, en horas, que un usuario permanece sin servicio eléctrico durante el año.": "Average time, in hours, that a user is without electricity service over the year.",

  /* --- Fuentes --- */
  "Elaboración propia con datos de la Empresa Nacional de Energía Eléctrica (ENEE) y la Comisión Reguladora de Energía Eléctrica (CREE), 2026.": "Own elaboration using data from the National Electric Power Company (ENEE) and the Electricity Regulatory Commission (CREE), 2026."
});

window.PAGE_TITLE = {es: "Sector El\u00e9ctrico \u2014 Estado del Pa\u00eds Honduras 2026", en: "Electricity Sector \u2014 State of the Nation Honduras 2026"};
